steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/genai-rag-confluence-ui', '-f', 'Dockerfile.streamlit', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/genai-rag-confluence-ui']
images:
  - 'gcr.io/$PROJECT_ID/genai-rag-confluence-ui'