FROM python:3.11-slim

RUN pip install --no-cache-dir poetry==1.6.1

RUN poetry config virtualenvs.create false

WORKDIR /code

COPY ./pyproject.toml ./README.md ./poetry.lock* ./

COPY ./streamlit ./streamlit
COPY ./app ./app

# Install main dependencies and Streamlit dependencies
RUN poetry install --no-interaction --no-ansi --no-dev && \
    poetry install --no-interaction --no-ansi --with streamlit

EXPOSE 8080

ENV STREAMLIT_SERVER_PORT=8080
ENV STREAMLIT_SERVER_ADDRESS=0.0.0.0

CMD ["streamlit", "run", "streamlit/streamlit_app.py"] 